#pragma once

#define LINE_BUFFER_SIZE 1024

#define TEST_DB_PATH "./tests/data/test.db"

#define KV_PARSER_TYPE_DELIMITER ":"
#define KV_PARSER_KEY_DELIMITER "="
#define KV_PARSER_VALUE_DELIMITER "\n"

#define KV_STORAGE_STRUCTURE_LIST "L"
#define KV_STORAGE_STRUCTURE_HASH "H"

#define KV_STORAGE_STRUCTURE KV_STORAGE_STRUCTURE_LIST
